In [1]:
"""
Nigel Deen
Class: CS 677
Date: Mon Sep 19 2022
Homework Problem #1 
Description: tests stock buy-and-sell strategies.
"""

'\nNigel Deen\nClass: CS 677\nDate: Mon Sep 19 2022\nHomework Problem #1 \nDescription: tests stock buy-and-sell strategies.\n'

In [2]:
import os
import statistics as stats
import pandas as pd
from operator import itemgetter

In [3]:
input_dir = os.path.abspath("")
ticker = "DIS"
ticker_file = os.path.join(input_dir, ticker + ".csv")

In [4]:
try:
    with open(ticker_file) as f:
        lines = f.read().splitlines()
    print("opened file for ticker: ", ticker)
    print(lines[0])
except Exception as e:
    print(e)
    print("failed to read stock data for ticker: ", ticker)

opened file for ticker:  DIS
Date,Year,Month,Day,Weekday,Week_Number,Year_Week,Open,High,Low,Close,Volume,Adj Close,Return,Short_MA,Long_MA

In [5]:
# each line represents a row of data the first line represents the columns
cols = lines[0].split(",")
cols

['Date',
 'Year',
 'Month',
 'Day',
 'Weekday',
 'Week_Number',
 'Year_Week',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Adj Close',
 'Return',
 'Short_MA',
 'Long_MA']

In [6]:
# create a container for the adjusted changes
date_l = []
year_l = []
weekday_l = []
ac_l = []

for row in lines[1:]:
    date = row.split(",")[0]
    date_l.append(date)

    year = row.split(",")[1]
    year_l.append(year)

    weekday = row.split(",")[4]
    weekday_l.append(weekday)

    ac = float(row.split(",")[12])
    ac_l.append(ac)

In [8]:
# look at the first 10 items
ac_l[:10]

[97.16, 95.19, 94.68, 93.87, 93.64, 94.27, 95.72, 92.91, 93.5, 88.59]

In [11]:
def daily_ret_pct_diff(l):
    """
    calculates the daily return and pct diff between a value and its predecessor in a list.
    """

    diff_l = []  # create an empty list to hold the results
    pct_diff_l = []  # create an empty list to hold the results
    i = 0  # identify starting point

    # loop through list
    for val in l[
        i : len(l)
    ]:  # iterater from the starting point to the last value in list

        if i == 0:
            diff = 0
            pct_diff = 0

        elif i == 1:
            diff = l[i] - l[0]  # calculate diff b/w values
            pct_diff = diff / l[0]  # calcuate the pct diff

        else:
            diff = l[i] - l[i - 1]  # calculate diff b/w values
            pct_diff = diff / l[i]  # calculate the pct diff

        diff_l.append(diff)
        pct_diff_l.append(pct_diff)  # append results to container
        i += 1  # increment from starting point

    return diff_l, pct_diff_l  # return the results

In [12]:
diff_l, pct_diff_l = daily_ret_pct_diff(ac_l)

In [13]:
# containers for returns by day of the week and year
mon_2016 = []
tue_2016 = []
wed_2016 = []
thu_2016 = []
fri_2016 = []

mon_2017 = []
tue_2017 = []
wed_2017 = []
thu_2017 = []
fri_2017 = []

mon_2018 = []
tue_2018 = []
wed_2018 = []
thu_2018 = []
fri_2018 = []

mon_2019 = []
tue_2019 = []
wed_2019 = []
thu_2019 = []
fri_2019 = []

mon_2020 = []
tue_2020 = []
wed_2020 = []
thu_2020 = []
fri_2020 = []

In [14]:
# loop through the returns and assign them by year and weekday to a container
for i in range(len(ac_l)):

    year = year_l[i]
    weekday = weekday_l[i]
    ret = pct_diff_l[i]

    # 2016
    if year == "2016" and weekday == "Monday":
        mon_2016.append(ret)
    if year == "2016" and weekday == "Tuesday":
        tue_2016.append(ret)
    if year == "2016" and weekday == "Wednesday":
        wed_2016.append(ret)
    if year == "2016" and weekday == "Thursday":
        thu_2016.append(ret)
    if year == "2016" and weekday == "Friday":
        fri_2016.append(ret)

    # 2017
    if year == "2017" and weekday == "Monday":
        mon_2017.append(ret)
    if year == "2017" and weekday == "Tuesday":
        tue_2017.append(ret)
    if year == "2017" and weekday == "Wednesday":
        wed_2017.append(ret)
    if year == "2017" and weekday == "Thursday":
        thu_2017.append(ret)
    if year == "2017" and weekday == "Friday":
        fri_2017.append(ret)

    # 2018
    if year == "2018" and weekday == "Monday":
        mon_2018.append(ret)
    if year == "2018" and weekday == "Tuesday":
        tue_2018.append(ret)
    if year == "2018" and weekday == "Wednesday":
        wed_2018.append(ret)
    if year == "2018" and weekday == "Thursday":
        thu_2018.append(ret)
    if year == "2018" and weekday == "Friday":
        fri_2018.append(ret)

    # 2019
    if year == "2019" and weekday == "Monday":
        mon_2019.append(ret)
    if year == "2019" and weekday == "Tuesday":
        tue_2019.append(ret)
    if year == "2019" and weekday == "Wednesday":
        wed_2019.append(ret)
    if year == "2019" and weekday == "Thursday":
        thu_2019.append(ret)
    if year == "2019" and weekday == "Friday":
        fri_2019.append(ret)

    # 2020
    if year == "2020" and weekday == "Monday":
        mon_2020.append(ret)
    if year == "2020" and weekday == "Tuesday":
        tue_2020.append(ret)
    if year == "2020" and weekday == "Wednesday":
        wed_2020.append(ret)
    if year == "2020" and weekday == "Thursday":
        thu_2020.append(ret)
    if year == "2020" and weekday == "Friday":
        fri_2020.append(ret)

In [15]:
# break up the daily returns by their sign

# 2016
mon_2016_pos = [x for x in mon_2016 if x > 0]
tue_2016_pos = [x for x in tue_2016 if x > 0]
wed_2016_pos = [x for x in wed_2016 if x > 0]
thu_2016_pos = [x for x in thu_2016 if x > 0]
fri_2016_pos = [x for x in fri_2016 if x > 0]

mon_2016_neg = [x for x in mon_2016 if x < 0]
tue_2016_neg = [x for x in tue_2016 if x < 0]
wed_2016_neg = [x for x in wed_2016 if x < 0]
thu_2016_neg = [x for x in thu_2016 if x < 0]
fri_2016_neg = [x for x in fri_2016 if x < 0]

# 2017
mon_2017_pos = [x for x in mon_2017 if x > 0]
tue_2017_pos = [x for x in tue_2017 if x > 0]
wed_2017_pos = [x for x in wed_2017 if x > 0]
thu_2017_pos = [x for x in thu_2017 if x > 0]
fri_2017_pos = [x for x in fri_2017 if x > 0]

mon_2017_neg = [x for x in mon_2017 if x < 0]
tue_2017_neg = [x for x in tue_2017 if x < 0]
wed_2017_neg = [x for x in wed_2017 if x < 0]
thu_2017_neg = [x for x in thu_2017 if x < 0]
fri_2017_neg = [x for x in fri_2017 if x < 0]

# 2018
mon_2018_pos = [x for x in mon_2018 if x > 0]
tue_2018_pos = [x for x in tue_2018 if x > 0]
wed_2018_pos = [x for x in wed_2018 if x > 0]
thu_2018_pos = [x for x in thu_2018 if x > 0]
fri_2018_pos = [x for x in fri_2018 if x > 0]

mon_2018_neg = [x for x in mon_2018 if x < 0]
tue_2018_neg = [x for x in tue_2018 if x < 0]
wed_2018_neg = [x for x in wed_2018 if x < 0]
thu_2018_neg = [x for x in thu_2018 if x < 0]
fri_2018_neg = [x for x in fri_2018 if x < 0]

# 2019
mon_2019_pos = [x for x in mon_2019 if x > 0]
tue_2019_pos = [x for x in tue_2019 if x > 0]
wed_2019_pos = [x for x in wed_2019 if x > 0]
thu_2019_pos = [x for x in thu_2019 if x > 0]
fri_2019_pos = [x for x in fri_2019 if x > 0]

mon_2019_neg = [x for x in mon_2019 if x < 0]
tue_2019_neg = [x for x in tue_2019 if x < 0]
wed_2019_neg = [x for x in wed_2019 if x < 0]
thu_2019_neg = [x for x in thu_2019 if x < 0]
fri_2019_neg = [x for x in fri_2019 if x < 0]

# 2020
mon_2020_pos = [x for x in mon_2020 if x > 0]
tue_2020_pos = [x for x in tue_2020 if x > 0]
wed_2020_pos = [x for x in wed_2020 if x > 0]
thu_2020_pos = [x for x in thu_2020 if x > 0]
fri_2020_pos = [x for x in fri_2020 if x > 0]

mon_2020_neg = [x for x in mon_2020 if x < 0]
tue_2020_neg = [x for x in tue_2020 if x < 0]
wed_2020_neg = [x for x in wed_2020 if x < 0]
thu_2020_neg = [x for x in thu_2020 if x < 0]
fri_2020_neg = [x for x in fri_2020 if x < 0]

In [16]:
# calculate mean and standard deviation of returns by day of the week and by year

# 2016
avg_mon_2016 = stats.mean(mon_2016)
stdev_mon_2016 = stats.stdev(mon_2016)

avg_tue_2016 = stats.mean(tue_2016)
stdev_tue_2016 = stats.stdev(tue_2016)

avg_wed_2016 = stats.mean(wed_2016)
stdev_wed_2016 = stats.stdev(wed_2016)

avg_thu_2016 = stats.mean(thu_2016)
stdev_thu_2016 = stats.stdev(thu_2016)

avg_fri_2016 = stats.mean(fri_2016)
stdev_fri_2016 = stats.stdev(fri_2016)

# 2017
avg_mon_2017 = stats.mean(mon_2017)
stdev_mon_2017 = stats.stdev(mon_2017)

avg_tue_2017 = stats.mean(tue_2017)
stdev_tue_2017 = stats.stdev(tue_2017)

avg_wed_2017 = stats.mean(wed_2017)
stdev_wed_2017 = stats.stdev(wed_2017)

avg_thu_2017 = stats.mean(thu_2017)
stdev_thu_2017 = stats.stdev(thu_2017)

avg_fri_2017 = stats.mean(fri_2017)
stdev_fri_2017 = stats.stdev(fri_2017)

# 2018
avg_mon_2018 = stats.mean(mon_2018)
stdev_mon_2018 = stats.stdev(mon_2018)

avg_tue_2018 = stats.mean(tue_2018)
stdev_tue_2018 = stats.stdev(tue_2018)

avg_wed_2018 = stats.mean(wed_2018)
stdev_wed_2018 = stats.stdev(wed_2018)

avg_thu_2018 = stats.mean(thu_2018)
stdev_thu_2018 = stats.stdev(thu_2018)

avg_fri_2018 = stats.mean(fri_2018)
stdev_fri_2018 = stats.stdev(fri_2018)

# 2019
avg_mon_2019 = stats.mean(mon_2019)
stdev_mon_2019 = stats.stdev(mon_2019)

avg_tue_2019 = stats.mean(tue_2019)
stdev_tue_2019 = stats.stdev(tue_2019)

avg_wed_2019 = stats.mean(wed_2019)
stdev_wed_2019 = stats.stdev(wed_2019)

avg_thu_2019 = stats.mean(thu_2019)
stdev_thu_2019 = stats.stdev(thu_2019)

avg_fri_2019 = stats.mean(fri_2019)
stdev_fri_2019 = stats.stdev(fri_2019)

# 2020
avg_mon_2020 = stats.mean(mon_2020)
stdev_mon_2020 = stats.stdev(mon_2020)

avg_tue_2020 = stats.mean(tue_2020)
stdev_tue_2020 = stats.stdev(tue_2020)

avg_wed_2020 = stats.mean(wed_2020)
stdev_wed_2020 = stats.stdev(wed_2020)

avg_thu_2020 = stats.mean(thu_2020)
stdev_thu_2020 = stats.stdev(thu_2020)

avg_fri_2020 = stats.mean(fri_2020)
stdev_fri_2020 = stats.stdev(fri_2020)

In [17]:
# calculate average returns and count

# 2016 - positive returns
avg_mon_2016_pos = stats.mean(mon_2016_pos)
num_mon_2016_pos = len(mon_2016_pos)
stdev_mon_2016_pos = stats.stdev(mon_2016_pos)

avg_tue_2016_pos = stats.mean(tue_2016_pos)
num_tue_2016_pos = len(tue_2016_pos)
stdev_tue_2016_pos = stats.stdev(tue_2016_pos)

avg_wed_2016_pos = stats.mean(wed_2016_pos)
num_wed_2016_pos = len(wed_2016_pos)
stdev_wed_2016_pos = stats.stdev(wed_2016_pos)

avg_thu_2016_pos = stats.mean(thu_2016_pos)
num_thu_2016_pos = len(thu_2016_pos)
stdev_thu_2016_pos = stats.stdev(thu_2016_pos)

avg_fri_2016_pos = stats.mean(fri_2016_pos)
num_fri_2016_pos = len(fri_2016_pos)
stdev_fri_2016_pos = stats.stdev(fri_2016_pos)

# 2016 - negative returns
avg_mon_2016_neg = stats.mean(mon_2016_neg)
num_mon_2016_neg = len(mon_2016_neg)
stdev_mon_2016_neg = stats.stdev(mon_2016_neg)

avg_tue_2016_neg = stats.mean(tue_2016_neg)
num_tue_2016_neg = len(tue_2016_neg)
stdev_tue_2016_neg = stats.stdev(tue_2016_neg)

avg_wed_2016_neg = stats.mean(wed_2016_neg)
num_wed_2016_neg = len(wed_2016_neg)
stdev_wed_2016_neg = stats.stdev(wed_2016_neg)

avg_thu_2016_neg = stats.mean(thu_2016_neg)
num_thu_2016_neg = len(thu_2016_neg)
stdev_thu_2016_neg = stats.stdev(thu_2016_neg)

avg_fri_2016_neg = stats.mean(fri_2016_neg)
num_fri_2016_neg = len(fri_2016_neg)
stdev_fri_2016_neg = stats.stdev(fri_2016_neg)

In [18]:
# calculate average returns and count

# 2017 - positive returns
avg_mon_2017_pos = stats.mean(mon_2017_pos)
num_mon_2017_pos = len(mon_2017_pos)
stdev_mon_2017_pos = stats.stdev(mon_2017_pos)

avg_tue_2017_pos = stats.mean(tue_2017_pos)
num_tue_2017_pos = len(tue_2017_pos)
stdev_tue_2017_pos = stats.stdev(tue_2017_pos)

avg_wed_2017_pos = stats.mean(wed_2017_pos)
num_wed_2017_pos = len(wed_2017_pos)
stdev_wed_2017_pos = stats.stdev(wed_2017_pos)

avg_thu_2017_pos = stats.mean(thu_2017_pos)
num_thu_2017_pos = len(thu_2017_pos)
stdev_thu_2017_pos = stats.stdev(thu_2017_pos)

avg_fri_2017_pos = stats.mean(fri_2017_pos)
num_fri_2017_pos = len(fri_2017_pos)
stdev_fri_2017_pos = stats.stdev(fri_2017_pos)

# 2017 - negative returns
avg_mon_2017_neg = stats.mean(mon_2017_neg)
num_mon_2017_neg = len(mon_2017_neg)
stdev_mon_2017_neg = stats.stdev(mon_2017_neg)

avg_tue_2017_neg = stats.mean(tue_2017_neg)
num_tue_2017_neg = len(tue_2017_neg)
stdev_tue_2017_neg = stats.stdev(tue_2017_neg)

avg_wed_2017_neg = stats.mean(wed_2017_neg)
num_wed_2017_neg = len(wed_2017_neg)
stdev_wed_2017_neg = stats.stdev(wed_2017_neg)

avg_thu_2017_neg = stats.mean(thu_2017_neg)
num_thu_2017_neg = len(thu_2017_neg)
stdev_thu_2017_neg = stats.stdev(thu_2017_neg)

avg_fri_2017_neg = stats.mean(fri_2017_neg)
num_fri_2017_neg = len(fri_2017_neg)
stdev_fri_2017_neg = stats.stdev(fri_2017_neg)

In [19]:
# calculate average returns and count

# 2018 - positive returns
avg_mon_2018_pos = stats.mean(mon_2018_pos)
num_mon_2018_pos = len(mon_2018_pos)
stdev_mon_2018_pos = stats.stdev(mon_2018_pos)

avg_tue_2018_pos = stats.mean(tue_2018_pos)
num_tue_2018_pos = len(tue_2018_pos)
stdev_tue_2018_pos = stats.stdev(tue_2018_pos)

avg_wed_2018_pos = stats.mean(wed_2018_pos)
num_wed_2018_pos = len(wed_2018_pos)
stdev_wed_2018_pos = stats.stdev(wed_2018_pos)

avg_thu_2018_pos = stats.mean(thu_2018_pos)
num_thu_2018_pos = len(thu_2018_pos)
stdev_thu_2018_pos = stats.stdev(thu_2018_pos)

avg_fri_2018_pos = stats.mean(fri_2018_pos)
num_fri_2018_pos = len(fri_2018_pos)
stdev_fri_2018_pos = stats.stdev(fri_2018_pos)

# 2018 - negative returns
avg_mon_2018_neg = stats.mean(mon_2018_neg)
num_mon_2018_neg = len(mon_2018_neg)
stdev_mon_2018_neg = stats.stdev(mon_2018_neg)

avg_tue_2018_neg = stats.mean(tue_2018_neg)
num_tue_2018_neg = len(tue_2018_neg)
stdev_tue_2018_neg = stats.stdev(tue_2018_neg)

avg_wed_2018_neg = stats.mean(wed_2018_neg)
num_wed_2018_neg = len(wed_2018_neg)
stdev_wed_2018_neg = stats.stdev(wed_2018_neg)

avg_thu_2018_neg = stats.mean(thu_2018_neg)
num_thu_2018_neg = len(thu_2018_neg)
stdev_thu_2018_neg = stats.stdev(thu_2018_neg)

avg_fri_2018_neg = stats.mean(fri_2018_neg)
num_fri_2018_neg = len(fri_2018_neg)
stdev_fri_2018_neg = stats.stdev(fri_2018_neg)

In [20]:
# calculate average returns and count

# 2019 - positive returns
avg_mon_2019_pos = stats.mean(mon_2019_pos)
num_mon_2019_pos = len(mon_2019_pos)
stdev_mon_2019_pos = stats.stdev(mon_2019_pos)

avg_tue_2019_pos = stats.mean(tue_2019_pos)
num_tue_2019_pos = len(tue_2019_pos)
stdev_tue_2019_pos = stats.stdev(tue_2019_pos)

avg_wed_2019_pos = stats.mean(wed_2019_pos)
num_wed_2019_pos = len(wed_2019_pos)
stdev_wed_2019_pos = stats.stdev(wed_2019_pos)

avg_thu_2019_pos = stats.mean(thu_2019_pos)
num_thu_2019_pos = len(thu_2019_pos)
stdev_thu_2019_pos = stats.stdev(thu_2019_pos)

avg_fri_2019_pos = stats.mean(fri_2019_pos)
num_fri_2019_pos = len(fri_2019_pos)
stdev_fri_2019_pos = stats.stdev(fri_2019_pos)

# 2019 - negative returns
avg_mon_2019_neg = stats.mean(mon_2019_neg)
num_mon_2019_neg = len(mon_2019_neg)
stdev_mon_2019_neg = stats.stdev(mon_2019_neg)

avg_tue_2019_neg = stats.mean(tue_2019_neg)
num_tue_2019_neg = len(tue_2019_neg)
stdev_tue_2019_neg = stats.stdev(tue_2019_neg)

avg_wed_2019_neg = stats.mean(wed_2019_neg)
num_wed_2019_neg = len(wed_2019_neg)
stdev_wed_2019_neg = stats.stdev(wed_2019_neg)

avg_thu_2019_neg = stats.mean(thu_2019_neg)
num_thu_2019_neg = len(thu_2019_neg)
stdev_thu_2019_neg = stats.stdev(thu_2019_neg)

avg_fri_2019_neg = stats.mean(fri_2019_neg)
num_fri_2019_neg = len(fri_2019_neg)
stdev_fri_2019_neg = stats.stdev(fri_2019_neg)

In [21]:
# calculate average returns and count

# 2020 - positive returns
avg_mon_2020_pos = stats.mean(mon_2020_pos)
num_mon_2020_pos = len(mon_2020_pos)
stdev_mon_2020_pos = stats.stdev(mon_2020_pos)

avg_tue_2020_pos = stats.mean(tue_2020_pos)
num_tue_2020_pos = len(tue_2020_pos)
stdev_tue_2020_pos = stats.stdev(tue_2020_pos)

avg_wed_2020_pos = stats.mean(wed_2020_pos)
num_wed_2020_pos = len(wed_2020_pos)
stdev_wed_2020_pos = stats.stdev(wed_2020_pos)

avg_thu_2020_pos = stats.mean(thu_2020_pos)
num_thu_2020_pos = len(thu_2020_pos)
stdev_thu_2020_pos = stats.stdev(thu_2020_pos)

avg_fri_2020_pos = stats.mean(fri_2020_pos)
num_fri_2020_pos = len(fri_2020_pos)
stdev_fri_2020_pos = stats.stdev(fri_2020_pos)

# 2020 - negative returns
avg_mon_2020_neg = stats.mean(mon_2020_neg)
num_mon_2020_neg = len(mon_2020_neg)
stdev_mon_2020_neg = stats.stdev(mon_2020_neg)

avg_tue_2020_neg = stats.mean(tue_2020_neg)
num_tue_2020_neg = len(tue_2020_neg)
stdev_tue_2020_neg = stats.stdev(tue_2020_neg)

avg_wed_2020_neg = stats.mean(wed_2020_neg)
num_wed_2020_neg = len(wed_2020_neg)
stdev_wed_2020_neg = stats.stdev(wed_2020_neg)

avg_thu_2020_neg = stats.mean(thu_2020_neg)
num_thu_2020_neg = len(thu_2020_neg)
stdev_thu_2020_neg = stats.stdev(thu_2020_neg)

avg_fri_2020_neg = stats.mean(fri_2020_neg)
num_fri_2020_neg = len(fri_2020_neg)
stdev_fri_2020_neg = stats.stdev(fri_2020_neg)

#### Create a summary table

In [22]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2016
res_2016 = pd.DataFrame(columns=cols)
res_2016["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2016["avg_return"] = [
    avg_mon_2016,
    avg_tue_2016,
    avg_wed_2016,
    avg_thu_2016,
    avg_fri_2016,
]

res_2016["stdev_return"] = [
    stdev_mon_2016,
    stdev_tue_2016,
    stdev_wed_2016,
    stdev_thu_2016,
    stdev_fri_2016,
]

res_2016["num_neg"] = [
    num_mon_2016_neg,
    num_tue_2016_neg,
    num_wed_2016_neg,
    num_thu_2016_neg,
    num_fri_2016_neg,
]

res_2016["avg_neg"] = [
    avg_mon_2016_neg,
    avg_tue_2016_neg,
    avg_wed_2016_neg,
    avg_thu_2016_neg,
    avg_fri_2016_neg,
]

res_2016["stdev_neg"] = [
    stdev_mon_2016_neg,
    stdev_tue_2016_neg,
    stdev_wed_2016_neg,
    stdev_thu_2016_neg,
    stdev_fri_2016_neg,
]

res_2016["num_pos"] = [
    num_mon_2016_pos,
    num_tue_2016_pos,
    num_wed_2016_pos,
    num_thu_2016_pos,
    num_fri_2016_pos,
]

res_2016["avg_pos"] = [
    avg_mon_2016_pos,
    avg_tue_2016_pos,
    avg_wed_2016_pos,
    avg_thu_2016_pos,
    avg_fri_2016_pos,
]

res_2016["stdev_pos"] = [
    stdev_mon_2016_pos,
    stdev_tue_2016_pos,
    stdev_wed_2016_pos,
    stdev_thu_2016_pos,
    stdev_fri_2016_pos,
]

In [23]:
res_2016.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,0.000811,0.009592,21,-0.007027,0.005327,23,0.008038,0.007006
1,Tue,-0.000499,0.009398,26,-0.007690,0.005622,25,0.006959,0.006388
2,Wed,-0.001065,0.012792,28,-0.009090,0.011040,23,0.008657,0.006994
3,Thu,0.001529,0.007759,23,-0.004977,0.003668,28,0.006873,0.005902
4,Fri,-0.000416,0.013413,28,-0.008249,0.011637,23,0.009119,0.008342

In [24]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2017
res_2017 = pd.DataFrame(columns=cols)
res_2017["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2017["avg_return"] = [
    avg_mon_2017,
    avg_tue_2017,
    avg_wed_2017,
    avg_thu_2017,
    avg_fri_2017,
]

res_2017["stdev_return"] = [
    stdev_mon_2017,
    stdev_tue_2017,
    stdev_wed_2017,
    stdev_thu_2017,
    stdev_fri_2017,
]

res_2017["num_neg"] = [
    num_mon_2017_neg,
    num_tue_2017_neg,
    num_wed_2017_neg,
    num_thu_2017_neg,
    num_fri_2017_neg,
]

res_2017["avg_neg"] = [
    avg_mon_2017_neg,
    avg_tue_2017_neg,
    avg_wed_2017_neg,
    avg_thu_2017_neg,
    avg_fri_2017_neg,
]

res_2017["stdev_neg"] = [
    stdev_mon_2017_neg,
    stdev_tue_2017_neg,
    stdev_wed_2017_neg,
    stdev_thu_2017_neg,
    stdev_fri_2017_neg,
]

res_2017["num_pos"] = [
    num_mon_2017_pos,
    num_tue_2017_pos,
    num_wed_2017_pos,
    num_thu_2017_pos,
    num_fri_2017_pos,
]

res_2017["avg_pos"] = [
    avg_mon_2017_pos,
    avg_tue_2017_pos,
    avg_wed_2017_pos,
    avg_thu_2017_pos,
    avg_fri_2017_pos,
]

res_2017["stdev_pos"] = [
    stdev_mon_2017_pos,
    stdev_tue_2017_pos,
    stdev_wed_2017_pos,
    stdev_thu_2017_pos,
    stdev_fri_2017_pos,
]

In [25]:
res_2017.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,0.002126,0.010151,25,-0.004345,0.002915,21,0.009830,0.010344
1,Tue,0.000559,0.008077,22,-0.006373,0.006422,29,0.005817,0.004379
2,Wed,-0.001370,0.010984,26,-0.009238,0.009912,25,0.006758,0.004248
3,Thu,-0.002199,0.011093,30,-0.008164,0.008984,21,0.006324,0.007808
4,Fri,0.001807,0.006259,23,-0.003497,0.003281,28,0.006163,0.004487

In [26]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2018
res_2018 = pd.DataFrame(columns=cols)
res_2018["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2018["avg_return"] = [
    avg_mon_2018,
    avg_tue_2018,
    avg_wed_2018,
    avg_thu_2018,
    avg_fri_2018,
]

res_2018["stdev_return"] = [
    stdev_mon_2018,
    stdev_tue_2018,
    stdev_wed_2018,
    stdev_thu_2018,
    stdev_fri_2018,
]

res_2018["num_neg"] = [
    num_mon_2018_neg,
    num_tue_2018_neg,
    num_wed_2018_neg,
    num_thu_2018_neg,
    num_fri_2018_neg,
]

res_2018["avg_neg"] = [
    avg_mon_2018_neg,
    avg_tue_2018_neg,
    avg_wed_2018_neg,
    avg_thu_2018_neg,
    avg_fri_2018_neg,
]

res_2018["stdev_neg"] = [
    stdev_mon_2018_neg,
    stdev_tue_2018_neg,
    stdev_wed_2018_neg,
    stdev_thu_2018_neg,
    stdev_fri_2018_neg,
]

res_2018["num_pos"] = [
    num_mon_2018_pos,
    num_tue_2018_pos,
    num_wed_2018_pos,
    num_thu_2018_pos,
    num_fri_2018_pos,
]

res_2018["avg_pos"] = [
    avg_mon_2018_pos,
    avg_tue_2018_pos,
    avg_wed_2018_pos,
    avg_thu_2018_pos,
    avg_fri_2018_pos,
]

res_2018["stdev_pos"] = [
    stdev_mon_2018_pos,
    stdev_tue_2018_pos,
    stdev_wed_2018_pos,
    stdev_thu_2018_pos,
    stdev_fri_2018_pos,
]

In [27]:
res_2018.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,-0.000509,0.012900,22,-0.010626,0.010644,26,0.008052,0.007169
1,Tue,-0.000788,0.014215,25,-0.011188,0.011036,26,0.009211,0.008664
2,Wed,-0.000055,0.015909,23,-0.011879,0.012475,27,0.010018,0.010783
3,Thu,0.001506,0.011752,23,-0.008835,0.007401,28,0.010000,0.006723
4,Fri,0.000080,0.011664,25,-0.009537,0.006258,25,0.009700,0.007177

In [28]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2019
res_2019 = pd.DataFrame(columns=cols)
res_2019["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2019["avg_return"] = [
    avg_mon_2019,
    avg_tue_2019,
    avg_wed_2019,
    avg_thu_2019,
    avg_fri_2019,
]

res_2019["stdev_return"] = [
    stdev_mon_2019,
    stdev_tue_2019,
    stdev_wed_2019,
    stdev_thu_2019,
    stdev_fri_2019,
]

res_2019["num_neg"] = [
    num_mon_2019_neg,
    num_tue_2019_neg,
    num_wed_2019_neg,
    num_thu_2019_neg,
    num_fri_2019_neg,
]

res_2019["avg_neg"] = [
    avg_mon_2019_neg,
    avg_tue_2019_neg,
    avg_wed_2019_neg,
    avg_thu_2019_neg,
    avg_fri_2019_neg,
]

res_2019["stdev_neg"] = [
    stdev_mon_2019_neg,
    stdev_tue_2019_neg,
    stdev_wed_2019_neg,
    stdev_thu_2019_neg,
    stdev_fri_2019_neg,
]

res_2019["num_pos"] = [
    num_mon_2019_pos,
    num_tue_2019_pos,
    num_wed_2019_pos,
    num_thu_2019_pos,
    num_fri_2019_pos,
]

res_2019["avg_pos"] = [
    avg_mon_2019_pos,
    avg_tue_2019_pos,
    avg_wed_2019_pos,
    avg_thu_2019_pos,
    avg_fri_2019_pos,
]

res_2019["stdev_pos"] = [
    stdev_mon_2019_pos,
    stdev_tue_2019_pos,
    stdev_wed_2019_pos,
    stdev_thu_2019_pos,
    stdev_fri_2019_pos,
]

In [29]:
res_2019.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,-0.001823,0.010988,27,-0.009572,0.006692,21,0.008140,0.006343
1,Tue,-0.000293,0.011303,28,-0.008460,0.007331,24,0.009234,0.006656
2,Wed,0.001428,0.015072,21,-0.009745,0.011743,30,0.009249,0.011953
3,Thu,0.001046,0.011688,20,-0.009419,0.006772,30,0.008023,0.008653
4,Fri,0.004748,0.017970,17,-0.007533,0.008410,34,0.010889,0.018396

In [30]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2020
res_2020 = pd.DataFrame(columns=cols)
res_2020["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2020["avg_return"] = [
    avg_mon_2020,
    avg_tue_2020,
    avg_wed_2020,
    avg_thu_2020,
    avg_fri_2020,
]

res_2020["stdev_return"] = [
    stdev_mon_2020,
    stdev_tue_2020,
    stdev_wed_2020,
    stdev_thu_2020,
    stdev_fri_2020,
]

res_2020["num_neg"] = [
    num_mon_2020_neg,
    num_tue_2020_neg,
    num_wed_2020_neg,
    num_thu_2020_neg,
    num_fri_2020_neg,
]

res_2020["avg_neg"] = [
    avg_mon_2020_neg,
    avg_tue_2020_neg,
    avg_wed_2020_neg,
    avg_thu_2020_neg,
    avg_fri_2020_neg,
]

res_2020["stdev_neg"] = [
    stdev_mon_2020_neg,
    stdev_tue_2020_neg,
    stdev_wed_2020_neg,
    stdev_thu_2020_neg,
    stdev_fri_2020_neg,
]

res_2020["num_pos"] = [
    num_mon_2020_pos,
    num_tue_2020_pos,
    num_wed_2020_pos,
    num_thu_2020_pos,
    num_fri_2020_pos,
]

res_2020["avg_pos"] = [
    avg_mon_2020_pos,
    avg_tue_2020_pos,
    avg_wed_2020_pos,
    avg_thu_2020_pos,
    avg_fri_2020_pos,
]

res_2020["stdev_pos"] = [
    stdev_mon_2020_pos,
    stdev_tue_2020_pos,
    stdev_wed_2020_pos,
    stdev_thu_2020_pos,
    stdev_fri_2020_pos,
]

In [31]:
res_2020.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,0.000344,0.035260,27,-0.022395,0.024122,21,0.029581,0.023867
1,Tue,0.004571,0.025912,26,-0.012261,0.011829,26,0.021403,0.025307
2,Wed,0.000179,0.025777,26,-0.019233,0.016115,26,0.019590,0.017664
3,Thu,-0.003485,0.032055,25,-0.023344,0.032420,26,0.015610,0.016507
4,Fri,0.000435,0.034122,28,-0.016918,0.024628,21,0.023572,0.031495

In [32]:
sum_tbls = [res_2016, res_2017, res_2018, res_2019, res_2020]

In [33]:
res_2016["year"] = 2016
res_2017["year"] = 2017
res_2018["year"] = 2018
res_2019["year"] = 2019
res_2020["year"] = 2020

summary_df = pd.concat(sum_tbls, axis=0).reset_index(drop=True)

In [34]:
summary_df.head(10)

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos,year
0,Mon,0.000811,0.009592,21,-0.007027,0.005327,23,0.008038,0.007006,2016
1,Tue,-0.000499,0.009398,26,-0.007690,0.005622,25,0.006959,0.006388,2016
2,Wed,-0.001065,0.012792,28,-0.009090,0.011040,23,0.008657,0.006994,2016
3,Thu,0.001529,0.007759,23,-0.004977,0.003668,28,0.006873,0.005902,2016
4,Fri,-0.000416,0.013413,28,-0.008249,0.011637,23,0.009119,0.008342,2016
5,Mon,0.002126,0.010151,25,-0.004345,0.002915,21,0.009830,0.010344,2017
6,Tue,0.000559,0.008077,22,-0.006373,0.006422,29,0.005817,0.004379,2017
7,Wed,-0.001370,0.010984,26,-0.009238,0.009912,25,0.006758,0.004248,2017
8,Thu,-0.002199,0.011093,30,-0.008164,0.008984,21,0.006324,0.007808,2017
9,Fri,0.001807,0.006259,23,-0.003497,0.003281,28,0.006163,0.004487,2017

#### 1.3 Are there more days with negative or non-negative returns?

In [35]:
# total number of days with a return, by year
tot_2016 = len(mon_2016) + len(tue_2016) + len(wed_2016) + len(thu_2016) + len(fri_2016)
tot_2017 = len(mon_2017) + len(tue_2017) + len(wed_2017) + len(thu_2017) + len(fri_2017)
tot_2018 = len(mon_2018) + len(tue_2018) + len(wed_2018) + len(thu_2018) + len(fri_2018)
tot_2019 = len(mon_2019) + len(tue_2019) + len(wed_2019) + len(thu_2019) + len(fri_2019)
tot_2020 = len(mon_2020) + len(tue_2020) + len(wed_2020) + len(thu_2020) + len(fri_2020)

In [36]:
tot_neg_days = 0
for tbl in sum_tbls:
    tot_neg_days = tot_neg_days + tbl["num_neg"].sum()

tot_nonneg_days = (tot_2016 + tot_2017 + tot_2018 + tot_2019 + tot_2020) - tot_neg_days

print("Days with non-negative returns: ", tot_nonneg_days)
print("Days with negative returns: ", tot_neg_days)

if tot_nonneg_days > tot_neg_days:
    print("There are more days with non-negative returns than negative returns.")
else:
    print("There are more days with negative returns than non-negative returns.")

Days with non-negative returns:  643
Days with negative returns:  615
There are more days with non-negative returns than negative returns.

#### 1.4 Does your stock lose more on a "down" day than it gains on an "up" day?

In [37]:
# take the average of averages of positive and negative returns
avg_pos_days = abs(stats.mean(summary_df["avg_pos"]))
avg_neg_days = abs(stats.mean(summary_df["avg_neg"]))

print("Average of positive returns: ", avg_pos_days)
print("Average of negative returns: ", avg_neg_days)

if avg_pos_days > avg_neg_days:
    print("Average positive returns are greater than average negative returns.")
else:
    print("Average negative returns are greater than average positive returns.")

Average of positive returns:  0.011072409927122712
Average of negative returns:  0.010383759557326969
Average positive returns are greater than average negative returns.

#### 1.5 Are these results the same across days of the week?

In [38]:
# average postive returns by day
summary_df.groupby("day")["avg_pos"].mean().sort_values()

day
Thu    0.009366
Tue    0.010525
Wed    0.010855
Fri    0.011889
Mon    0.012728
Name: avg_pos, dtype: float64

In [39]:
# average negative returns by day
summary_df.groupby("day")["avg_neg"].mean().sort_values()

day
Wed   -0.011837
Thu   -0.010948
Mon   -0.010793
Tue   -0.009194
Fri   -0.009147
Name: avg_neg, dtype: float64

The stock fluctuates the most on Friday (second largest average positive return and largest negative average return). The highest average return occurs on Thursday but the second highest average loss occurs on Thursday. Thursdays seem to be risky day to buy or sell stocks.

#### 2.1 Are there any patterns across days of the week?

In [40]:
# average returns by day
summary_df.groupby("day")["avg_return"].mean()

day
Fri    0.001331
Mon    0.000190
Thu   -0.000320
Tue    0.000710
Wed   -0.000177
Name: avg_return, dtype: float64

The changes fluctuate slightly between positive and negative but these are extremely small differences. Friday seems to be the outlier yielding the highest average return.

#### 2.2 Are there any patterns across different years for the same day of the week?

In [41]:
# average returns by day and by year
summary_df.groupby(["day", "year"])["avg_return"].mean()

day  year
Fri  2016   -0.000416
     2017    0.001807
     2018    0.000080
     2019    0.004748
     2020    0.000435
Mon  2016    0.000811
     2017    0.002126
     2018   -0.000509
     2019   -0.001823
     2020    0.000344
Thu  2016    0.001529
     2017   -0.002199
     2018    0.001506
     2019    0.001046
     2020   -0.003485
Tue  2016   -0.000499
     2017    0.000559
     2018   -0.000788
     2019   -0.000293
     2020    0.004571
Wed  2016   -0.001065
     2017   -0.001370
     2018   -0.000055
     2019    0.001428
     2020    0.000179
Name: avg_return, dtype: float64

There does not seem to be a discernable pattern across different years for the same day of the week.

#### 2.3 What are the best and worst days of the week to be invested for each year.

In [42]:
# average returns by year and by day
summary_df.groupby(["year", "day"])["avg_return"].mean()

year  day
2016  Fri   -0.000416
      Mon    0.000811
      Thu    0.001529
      Tue   -0.000499
      Wed   -0.001065
2017  Fri    0.001807
      Mon    0.002126
      Thu   -0.002199
      Tue    0.000559
      Wed   -0.001370
2018  Fri    0.000080
      Mon   -0.000509
      Thu    0.001506
      Tue   -0.000788
      Wed   -0.000055
2019  Fri    0.004748
      Mon   -0.001823
      Thu    0.001046
      Tue   -0.000293
      Wed    0.001428
2020  Fri    0.000435
      Mon    0.000344
      Thu   -0.003485
      Tue    0.004571
      Wed    0.000179
Name: avg_return, dtype: float64

2016
- Best Day: Thursday
- Worst Day: Wednesday

2017
- Best Day: Friday
- Worst Day: Thursday

2018
- Best Day: Thursday
- Worst Day: Tuesday

2019
- Best Day: Friday
- Worst Day: Monday

2020
- Best Day: Tuesday
- Worst Day: Thursday

#### 2.4 Do these days change from year to year for your stock?
- Yes, for the most part, the best days occur towards the end of the week (Thursdays and Fridays) while the worst days tend to fluctuate across all five days in the week.

#### 3. Compute the aggregate table across all 5 years, one table for both your stock and one table for S&P-500 (using data for "spy").

In [43]:
# import the spy data
input_dir = os.path.abspath("")
ticker = "SPY"
ticker_file = os.path.join(input_dir, ticker + ".csv")

In [44]:
try:
    with open(ticker_file) as f:
        lines = f.read().splitlines()
    print("opened file for ticker: ", ticker)
    print(lines[0])
except Exception as e:
    print(e)
    print("failed to read stock data for ticker: ", ticker)

opened file for ticker:  SPY
Date,Year,Month,Day,Weekday,Week_Number,Year_Week,Open,High,Low,Close,Volume,Adj Close,Return,Short_MA,Long_MA

In [45]:
# each line represents a row of data
# the first line represents the columns
cols = lines[0].split(",")
cols

['Date',
 'Year',
 'Month',
 'Day',
 'Weekday',
 'Week_Number',
 'Year_Week',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Adj Close',
 'Return',
 'Short_MA',
 'Long_MA']

In [46]:
spy_date_l = []
spy_year_l = []
spy_weekday_l = []
spy_ac_l = []

for row in lines[1:]:
    date = row.split(",")[0]
    spy_date_l.append(date)

    year = row.split(",")[1]
    spy_year_l.append(year)

    weekday = row.split(",")[4]
    spy_weekday_l.append(weekday)

    ac = float(row.split(",")[12])
    spy_ac_l.append(ac)

In [47]:
spy_ac_l[:5]

[178.05, 178.35, 176.1, 171.88, 169.99]

In [48]:
diff_l, pct_diff_l = daily_ret_pct_diff(spy_ac_l)

In [49]:
# containers for returns by day of the week and year
mon_2016 = []
tue_2016 = []
wed_2016 = []
thu_2016 = []
fri_2016 = []

mon_2017 = []
tue_2017 = []
wed_2017 = []
thu_2017 = []
fri_2017 = []

mon_2018 = []
tue_2018 = []
wed_2018 = []
thu_2018 = []
fri_2018 = []

mon_2019 = []
tue_2019 = []
wed_2019 = []
thu_2019 = []
fri_2019 = []

mon_2020 = []
tue_2020 = []
wed_2020 = []
thu_2020 = []
fri_2020 = []

In [50]:
len(pct_diff_l)

1258

In [51]:
for i in range(len(spy_ac_l)):
    year = spy_year_l[i]
    weekday = spy_weekday_l[i]
    ret = pct_diff_l[i]

    # 2016
    if year == "2016" and weekday == "Monday":
        mon_2016.append(ret)
    if year == "2016" and weekday == "Tuesday":
        tue_2016.append(ret)
    if year == "2016" and weekday == "Wednesday":
        wed_2016.append(ret)
    if year == "2016" and weekday == "Thursday":
        thu_2016.append(ret)
    if year == "2016" and weekday == "Friday":
        fri_2016.append(ret)

    # 2017
    if year == "2017" and weekday == "Monday":
        mon_2017.append(ret)
    if year == "2017" and weekday == "Tuesday":
        tue_2017.append(ret)
    if year == "2017" and weekday == "Wednesday":
        wed_2017.append(ret)
    if year == "2017" and weekday == "Thursday":
        thu_2017.append(ret)
    if year == "2017" and weekday == "Friday":
        fri_2017.append(ret)

    # 2018
    if year == "2018" and weekday == "Monday":
        mon_2018.append(ret)
    if year == "2018" and weekday == "Tuesday":
        tue_2018.append(ret)
    if year == "2018" and weekday == "Wednesday":
        wed_2018.append(ret)
    if year == "2018" and weekday == "Thursday":
        thu_2018.append(ret)
    if year == "2018" and weekday == "Friday":
        fri_2018.append(ret)

    # 2019
    if year == "2019" and weekday == "Monday":
        mon_2019.append(ret)
    if year == "2019" and weekday == "Tuesday":
        tue_2019.append(ret)
    if year == "2019" and weekday == "Wednesday":
        wed_2019.append(ret)
    if year == "2019" and weekday == "Thursday":
        thu_2019.append(ret)
    if year == "2019" and weekday == "Friday":
        fri_2019.append(ret)

    # 2020
    if year == "2020" and weekday == "Monday":
        mon_2020.append(ret)
    if year == "2020" and weekday == "Tuesday":
        tue_2020.append(ret)
    if year == "2020" and weekday == "Wednesday":
        wed_2020.append(ret)
    if year == "2020" and weekday == "Thursday":
        thu_2020.append(ret)
    if year == "2020" and weekday == "Friday":
        fri_2020.append(ret)

In [52]:
# containers for returns by day of the week, year, and sign of the return

# 2016
mon_2016_pos = [x for x in mon_2016 if x > 0]
tue_2016_pos = [x for x in tue_2016 if x > 0]
wed_2016_pos = [x for x in wed_2016 if x > 0]
thu_2016_pos = [x for x in thu_2016 if x > 0]
fri_2016_pos = [x for x in fri_2016 if x > 0]

mon_2016_neg = [x for x in mon_2016 if x < 0]
tue_2016_neg = [x for x in tue_2016 if x < 0]
wed_2016_neg = [x for x in wed_2016 if x < 0]
thu_2016_neg = [x for x in thu_2016 if x < 0]
fri_2016_neg = [x for x in fri_2016 if x < 0]

# 2017
mon_2017_pos = [x for x in mon_2017 if x > 0]
tue_2017_pos = [x for x in tue_2017 if x > 0]
wed_2017_pos = [x for x in wed_2017 if x > 0]
thu_2017_pos = [x for x in thu_2017 if x > 0]
fri_2017_pos = [x for x in fri_2017 if x > 0]

mon_2017_neg = [x for x in mon_2017 if x < 0]
tue_2017_neg = [x for x in tue_2017 if x < 0]
wed_2017_neg = [x for x in wed_2017 if x < 0]
thu_2017_neg = [x for x in thu_2017 if x < 0]
fri_2017_neg = [x for x in fri_2017 if x < 0]

# 2018
mon_2018_pos = [x for x in mon_2018 if x > 0]
tue_2018_pos = [x for x in tue_2018 if x > 0]
wed_2018_pos = [x for x in wed_2018 if x > 0]
thu_2018_pos = [x for x in thu_2018 if x > 0]
fri_2018_pos = [x for x in fri_2018 if x > 0]

mon_2018_neg = [x for x in mon_2018 if x < 0]
tue_2018_neg = [x for x in tue_2018 if x < 0]
wed_2018_neg = [x for x in wed_2018 if x < 0]
thu_2018_neg = [x for x in thu_2018 if x < 0]
fri_2018_neg = [x for x in fri_2018 if x < 0]

# 2019
mon_2019_pos = [x for x in mon_2019 if x > 0]
tue_2019_pos = [x for x in tue_2019 if x > 0]
wed_2019_pos = [x for x in wed_2019 if x > 0]
thu_2019_pos = [x for x in thu_2019 if x > 0]
fri_2019_pos = [x for x in fri_2019 if x > 0]

mon_2019_neg = [x for x in mon_2019 if x < 0]
tue_2019_neg = [x for x in tue_2019 if x < 0]
wed_2019_neg = [x for x in wed_2019 if x < 0]
thu_2019_neg = [x for x in thu_2019 if x < 0]
fri_2019_neg = [x for x in fri_2019 if x < 0]

# 2020
mon_2020_pos = [x for x in mon_2020 if x > 0]
tue_2020_pos = [x for x in tue_2020 if x > 0]
wed_2020_pos = [x for x in wed_2020 if x > 0]
thu_2020_pos = [x for x in thu_2020 if x > 0]
fri_2020_pos = [x for x in fri_2020 if x > 0]

mon_2020_neg = [x for x in mon_2020 if x < 0]
tue_2020_neg = [x for x in tue_2020 if x < 0]
wed_2020_neg = [x for x in wed_2020 if x < 0]
thu_2020_neg = [x for x in thu_2020 if x < 0]
fri_2020_neg = [x for x in fri_2020 if x < 0]

In [53]:
# calculate mean and standard deviation of returns by day of the week and by year

# 2016
avg_mon_2016 = stats.mean(mon_2016)
stdev_mon_2016 = stats.stdev(mon_2016)

avg_tue_2016 = stats.mean(tue_2016)
stdev_tue_2016 = stats.stdev(tue_2016)

avg_wed_2016 = stats.mean(wed_2016)
stdev_wed_2016 = stats.stdev(wed_2016)

avg_thu_2016 = stats.mean(thu_2016)
stdev_thu_2016 = stats.stdev(thu_2016)

avg_fri_2016 = stats.mean(fri_2016)
stdev_fri_2016 = stats.stdev(fri_2016)

# 2017
avg_mon_2017 = stats.mean(mon_2017)
stdev_mon_2017 = stats.stdev(mon_2017)

avg_tue_2017 = stats.mean(tue_2017)
stdev_tue_2017 = stats.stdev(tue_2017)

avg_wed_2017 = stats.mean(wed_2017)
stdev_wed_2017 = stats.stdev(wed_2017)

avg_thu_2017 = stats.mean(thu_2017)
stdev_thu_2017 = stats.stdev(thu_2017)

avg_fri_2017 = stats.mean(fri_2017)
stdev_fri_2017 = stats.stdev(fri_2017)

# 2018
avg_mon_2018 = stats.mean(mon_2018)
stdev_mon_2018 = stats.stdev(mon_2018)

avg_tue_2018 = stats.mean(tue_2018)
stdev_tue_2018 = stats.stdev(tue_2018)

avg_wed_2018 = stats.mean(wed_2018)
stdev_wed_2018 = stats.stdev(wed_2018)

avg_thu_2018 = stats.mean(thu_2018)
stdev_thu_2018 = stats.stdev(thu_2018)

avg_fri_2018 = stats.mean(fri_2018)
stdev_fri_2018 = stats.stdev(fri_2018)

# 2019
avg_mon_2019 = stats.mean(mon_2019)
stdev_mon_2019 = stats.stdev(mon_2019)

avg_tue_2019 = stats.mean(tue_2019)
stdev_tue_2019 = stats.stdev(tue_2019)

avg_wed_2019 = stats.mean(wed_2019)
stdev_wed_2019 = stats.stdev(wed_2019)

avg_thu_2019 = stats.mean(thu_2019)
stdev_thu_2019 = stats.stdev(thu_2019)

avg_fri_2019 = stats.mean(fri_2019)
stdev_fri_2019 = stats.stdev(fri_2019)

In [54]:
# calculate average returns and length

# 2016 - positive returns
avg_mon_2016_pos = stats.mean(mon_2016_pos)
num_mon_2016_pos = len(mon_2016_pos)
stdev_mon_2016_pos = stats.stdev(mon_2016_pos)

avg_tue_2016_pos = stats.mean(tue_2016_pos)
num_tue_2016_pos = len(tue_2016_pos)
stdev_tue_2016_pos = stats.stdev(tue_2016_pos)

avg_wed_2016_pos = stats.mean(wed_2016_pos)
num_wed_2016_pos = len(wed_2016_pos)
stdev_wed_2016_pos = stats.stdev(wed_2016_pos)

avg_thu_2016_pos = stats.mean(thu_2016_pos)
num_thu_2016_pos = len(thu_2016_pos)
stdev_thu_2016_pos = stats.stdev(thu_2016_pos)

avg_fri_2016_pos = stats.mean(fri_2016_pos)
num_fri_2016_pos = len(fri_2016_pos)
stdev_fri_2016_pos = stats.stdev(fri_2016_pos)

# 2016 - negative returns
avg_mon_2016_neg = stats.mean(mon_2016_neg)
num_mon_2016_neg = len(mon_2016_neg)
stdev_mon_2016_neg = stats.stdev(mon_2016_neg)

avg_tue_2016_neg = stats.mean(tue_2016_neg)
num_tue_2016_neg = len(tue_2016_neg)
stdev_tue_2016_neg = stats.stdev(tue_2016_neg)

avg_wed_2016_neg = stats.mean(wed_2016_neg)
num_wed_2016_neg = len(wed_2016_neg)
stdev_wed_2016_neg = stats.stdev(wed_2016_neg)

avg_thu_2016_neg = stats.mean(thu_2016_neg)
num_thu_2016_neg = len(thu_2016_neg)
stdev_thu_2016_neg = stats.stdev(thu_2016_neg)

avg_fri_2016_neg = stats.mean(fri_2016_neg)
num_fri_2016_neg = len(fri_2016_neg)
stdev_fri_2016_neg = stats.stdev(fri_2016_neg)

In [55]:
# calculate average returns and length

# 2017 - positive returns
avg_mon_2017_pos = stats.mean(mon_2017_pos)
num_mon_2017_pos = len(mon_2017_pos)
stdev_mon_2017_pos = stats.stdev(mon_2017_pos)

avg_tue_2017_pos = stats.mean(tue_2017_pos)
num_tue_2017_pos = len(tue_2017_pos)
stdev_tue_2017_pos = stats.stdev(tue_2017_pos)

avg_wed_2017_pos = stats.mean(wed_2017_pos)
num_wed_2017_pos = len(wed_2017_pos)
stdev_wed_2017_pos = stats.stdev(wed_2017_pos)

avg_thu_2017_pos = stats.mean(thu_2017_pos)
num_thu_2017_pos = len(thu_2017_pos)
stdev_thu_2017_pos = stats.stdev(thu_2017_pos)

avg_fri_2017_pos = stats.mean(fri_2017_pos)
num_fri_2017_pos = len(fri_2017_pos)
stdev_fri_2017_pos = stats.stdev(fri_2017_pos)

# 2017 - negative returns
avg_mon_2017_neg = stats.mean(mon_2017_neg)
num_mon_2017_neg = len(mon_2017_neg)
stdev_mon_2017_neg = stats.stdev(mon_2017_neg)

avg_tue_2017_neg = stats.mean(tue_2017_neg)
num_tue_2017_neg = len(tue_2017_neg)
stdev_tue_2017_neg = stats.stdev(tue_2017_neg)

avg_wed_2017_neg = stats.mean(wed_2017_neg)
num_wed_2017_neg = len(wed_2017_neg)
stdev_wed_2017_neg = stats.stdev(wed_2017_neg)

avg_thu_2017_neg = stats.mean(thu_2017_neg)
num_thu_2017_neg = len(thu_2017_neg)
stdev_thu_2017_neg = stats.stdev(thu_2017_neg)

avg_fri_2017_neg = stats.mean(fri_2017_neg)
num_fri_2017_neg = len(fri_2017_neg)
stdev_fri_2017_neg = stats.stdev(fri_2017_neg)

In [56]:
# calculate average returns and length

# 2018 - positive returns
avg_mon_2018_pos = stats.mean(mon_2018_pos)
num_mon_2018_pos = len(mon_2018_pos)
stdev_mon_2018_pos = stats.stdev(mon_2018_pos)

avg_tue_2018_pos = stats.mean(tue_2018_pos)
num_tue_2018_pos = len(tue_2018_pos)
stdev_tue_2018_pos = stats.stdev(tue_2018_pos)

avg_wed_2018_pos = stats.mean(wed_2018_pos)
num_wed_2018_pos = len(wed_2018_pos)
stdev_wed_2018_pos = stats.stdev(wed_2018_pos)

avg_thu_2018_pos = stats.mean(thu_2018_pos)
num_thu_2018_pos = len(thu_2018_pos)
stdev_thu_2018_pos = stats.stdev(thu_2018_pos)

avg_fri_2018_pos = stats.mean(fri_2018_pos)
num_fri_2018_pos = len(fri_2018_pos)
stdev_fri_2018_pos = stats.stdev(fri_2018_pos)

# 2018 - negative returns
avg_mon_2018_neg = stats.mean(mon_2018_neg)
num_mon_2018_neg = len(mon_2018_neg)
stdev_mon_2018_neg = stats.stdev(mon_2018_neg)

avg_tue_2018_neg = stats.mean(tue_2018_neg)
num_tue_2018_neg = len(tue_2018_neg)
stdev_tue_2018_neg = stats.stdev(tue_2018_neg)

avg_wed_2018_neg = stats.mean(wed_2018_neg)
num_wed_2018_neg = len(wed_2018_neg)
stdev_wed_2018_neg = stats.stdev(wed_2018_neg)

avg_thu_2018_neg = stats.mean(thu_2018_neg)
num_thu_2018_neg = len(thu_2018_neg)
stdev_thu_2018_neg = stats.stdev(thu_2018_neg)

avg_fri_2018_neg = stats.mean(fri_2018_neg)
num_fri_2018_neg = len(fri_2018_neg)
stdev_fri_2018_neg = stats.stdev(fri_2018_neg)

In [57]:
# calculate average returns and length

# 2019 - positive returns
avg_mon_2019_pos = stats.mean(mon_2019_pos)
num_mon_2019_pos = len(mon_2019_pos)
stdev_mon_2019_pos = stats.stdev(mon_2019_pos)

avg_tue_2019_pos = stats.mean(tue_2019_pos)
num_tue_2019_pos = len(tue_2019_pos)
stdev_tue_2019_pos = stats.stdev(tue_2019_pos)

avg_wed_2019_pos = stats.mean(wed_2019_pos)
num_wed_2019_pos = len(wed_2019_pos)
stdev_wed_2019_pos = stats.stdev(wed_2019_pos)

avg_thu_2019_pos = stats.mean(thu_2019_pos)
num_thu_2019_pos = len(thu_2019_pos)
stdev_thu_2019_pos = stats.stdev(thu_2019_pos)

avg_fri_2019_pos = stats.mean(fri_2019_pos)
num_fri_2019_pos = len(fri_2019_pos)
stdev_fri_2019_pos = stats.stdev(fri_2019_pos)

# 2019 - negative returns
avg_mon_2019_neg = stats.mean(mon_2019_neg)
num_mon_2019_neg = len(mon_2019_neg)
stdev_mon_2019_neg = stats.stdev(mon_2019_neg)

avg_tue_2019_neg = stats.mean(tue_2019_neg)
num_tue_2019_neg = len(tue_2019_neg)
stdev_tue_2019_neg = stats.stdev(tue_2019_neg)

avg_wed_2019_neg = stats.mean(wed_2019_neg)
num_wed_2019_neg = len(wed_2019_neg)
stdev_wed_2019_neg = stats.stdev(wed_2019_neg)

avg_thu_2019_neg = stats.mean(thu_2019_neg)
num_thu_2019_neg = len(thu_2019_neg)
stdev_thu_2019_neg = stats.stdev(thu_2019_neg)

avg_fri_2019_neg = stats.mean(fri_2019_neg)
num_fri_2019_neg = len(fri_2019_neg)
stdev_fri_2019_neg = stats.stdev(fri_2019_neg)

### Create a summary table

In [58]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2016
res_2016 = pd.DataFrame(columns=cols)
res_2016["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2016["avg_return"] = [
    avg_mon_2016,
    avg_tue_2016,
    avg_wed_2016,
    avg_thu_2016,
    avg_fri_2016,
]

res_2016["stdev_return"] = [
    stdev_mon_2016,
    stdev_tue_2016,
    stdev_wed_2016,
    stdev_thu_2016,
    stdev_fri_2016,
]

res_2016["num_neg"] = [
    num_mon_2016_neg,
    num_tue_2016_neg,
    num_wed_2016_neg,
    num_thu_2016_neg,
    num_fri_2016_neg,
]

res_2016["avg_neg"] = [
    avg_mon_2016_neg,
    avg_tue_2016_neg,
    avg_wed_2016_neg,
    avg_thu_2016_neg,
    avg_fri_2016_neg,
]

res_2016["stdev_neg"] = [
    stdev_mon_2016_neg,
    stdev_tue_2016_neg,
    stdev_wed_2016_neg,
    stdev_thu_2016_neg,
    stdev_fri_2016_neg,
]

res_2016["num_pos"] = [
    num_mon_2016_pos,
    num_tue_2016_pos,
    num_wed_2016_pos,
    num_thu_2016_pos,
    num_fri_2016_pos,
]

res_2016["avg_pos"] = [
    avg_mon_2016_pos,
    avg_tue_2016_pos,
    avg_wed_2016_pos,
    avg_thu_2016_pos,
    avg_fri_2016_pos,
]

res_2016["stdev_pos"] = [
    stdev_mon_2016_pos,
    stdev_tue_2016_pos,
    stdev_wed_2016_pos,
    stdev_thu_2016_pos,
    stdev_fri_2016_pos,
]

In [59]:
res_2016.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,0.000726,0.007204,20,-0.004873,0.005343,25,0.005233,0.005234
1,Tue,0.000980,0.008423,20,-0.007061,0.005106,32,0.006005,0.005742
2,Wed,0.000581,0.007656,24,-0.005499,0.005863,28,0.005792,0.004519
3,Thu,0.000378,0.006878,23,-0.004820,0.005645,28,0.004648,0.004440
4,Fri,-0.000291,0.010502,26,-0.006973,0.009026,24,0.006934,0.006802

In [60]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2017
res_2017 = pd.DataFrame(columns=cols)
res_2017["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2017["avg_return"] = [
    avg_mon_2017,
    avg_tue_2017,
    avg_wed_2017,
    avg_thu_2017,
    avg_fri_2017,
]

res_2017["stdev_return"] = [
    stdev_mon_2017,
    stdev_tue_2017,
    stdev_wed_2017,
    stdev_thu_2017,
    stdev_fri_2017,
]

res_2017["num_neg"] = [
    num_mon_2017_neg,
    num_tue_2017_neg,
    num_wed_2017_neg,
    num_thu_2017_neg,
    num_fri_2017_neg,
]

res_2017["avg_neg"] = [
    avg_mon_2017_neg,
    avg_tue_2017_neg,
    avg_wed_2017_neg,
    avg_thu_2017_neg,
    avg_fri_2017_neg,
]

res_2017["stdev_neg"] = [
    stdev_mon_2017_neg,
    stdev_tue_2017_neg,
    stdev_wed_2017_neg,
    stdev_thu_2017_neg,
    stdev_fri_2017_neg,
]

res_2017["num_pos"] = [
    num_mon_2017_pos,
    num_tue_2017_pos,
    num_wed_2017_pos,
    num_thu_2017_pos,
    num_fri_2017_pos,
]

res_2017["avg_pos"] = [
    avg_mon_2017_pos,
    avg_tue_2017_pos,
    avg_wed_2017_pos,
    avg_thu_2017_pos,
    avg_fri_2017_pos,
]

res_2017["stdev_pos"] = [
    stdev_mon_2017_pos,
    stdev_tue_2017_pos,
    stdev_wed_2017_pos,
    stdev_thu_2017_pos,
    stdev_fri_2017_pos,
]

In [61]:
res_2017.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,0.001321,0.003908,20,-0.001798,0.001596,26,0.003721,0.003432
1,Tue,0.000397,0.004457,23,-0.003194,0.003072,27,0.003471,0.003000
2,Wed,0.001061,0.004507,19,-0.002602,0.004096,33,0.003169,0.003223
3,Thu,-0.000232,0.005003,25,-0.003806,0.004219,26,0.003203,0.002816
4,Fri,0.001369,0.003009,20,-0.001569,0.000968,31,0.003264,0.002243

In [62]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2018
res_2018 = pd.DataFrame(columns=cols)
res_2018["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2018["avg_return"] = [
    avg_mon_2018,
    avg_tue_2018,
    avg_wed_2018,
    avg_thu_2018,
    avg_fri_2018,
]

res_2018["stdev_return"] = [
    stdev_mon_2018,
    stdev_tue_2018,
    stdev_wed_2018,
    stdev_thu_2018,
    stdev_fri_2018,
]

res_2018["num_neg"] = [
    num_mon_2018_neg,
    num_tue_2018_neg,
    num_wed_2018_neg,
    num_thu_2018_neg,
    num_fri_2018_neg,
]

res_2018["avg_neg"] = [
    avg_mon_2018_neg,
    avg_tue_2018_neg,
    avg_wed_2018_neg,
    avg_thu_2018_neg,
    avg_fri_2018_neg,
]

res_2018["stdev_neg"] = [
    stdev_mon_2018_neg,
    stdev_tue_2018_neg,
    stdev_wed_2018_neg,
    stdev_thu_2018_neg,
    stdev_fri_2018_neg,
]

res_2018["num_pos"] = [
    num_mon_2018_pos,
    num_tue_2018_pos,
    num_wed_2018_pos,
    num_thu_2018_pos,
    num_fri_2018_pos,
]

res_2018["avg_pos"] = [
    avg_mon_2018_pos,
    avg_tue_2018_pos,
    avg_wed_2018_pos,
    avg_thu_2018_pos,
    avg_fri_2018_pos,
]

res_2018["stdev_pos"] = [
    stdev_mon_2018_pos,
    stdev_tue_2018_pos,
    stdev_wed_2018_pos,
    stdev_thu_2018_pos,
    stdev_fri_2018_pos,
]

In [63]:
res_2018.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,-0.001001,0.012150,21,-0.010904,0.010831,26,0.006960,0.005948
1,Tue,0.000054,0.009435,21,-0.007810,0.008057,29,0.005751,0.005709
2,Wed,0.000918,0.012009,24,-0.006906,0.008499,26,0.008139,0.010159
3,Thu,-0.000198,0.010332,27,-0.007039,0.009411,24,0.007497,0.003900
4,Fri,-0.001015,0.010193,23,-0.009281,0.008503,28,0.005774,0.005242

In [64]:
# create a dataframe with all the results per year
cols = [
    "day",
    "avg_return",
    "stdev_return",
    "num_neg",
    "avg_neg",
    "stdev_neg",
    "num_pos",
    "avg_pos",
    "stdev_pos",
]

# 2019
res_2019 = pd.DataFrame(columns=cols)
res_2019["day"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]

res_2019["avg_return"] = [
    avg_mon_2019,
    avg_tue_2019,
    avg_wed_2019,
    avg_thu_2019,
    avg_fri_2019,
]

res_2019["stdev_return"] = [
    stdev_mon_2019,
    stdev_tue_2019,
    stdev_wed_2019,
    stdev_thu_2019,
    stdev_fri_2019,
]

res_2019["num_neg"] = [
    num_mon_2019_neg,
    num_tue_2019_neg,
    num_wed_2019_neg,
    num_thu_2019_neg,
    num_fri_2019_neg,
]

res_2019["avg_neg"] = [
    avg_mon_2019_neg,
    avg_tue_2019_neg,
    avg_wed_2019_neg,
    avg_thu_2019_neg,
    avg_fri_2019_neg,
]

res_2019["stdev_neg"] = [
    stdev_mon_2019_neg,
    stdev_tue_2019_neg,
    stdev_wed_2019_neg,
    stdev_thu_2019_neg,
    stdev_fri_2019_neg,
]

res_2019["num_pos"] = [
    num_mon_2019_pos,
    num_tue_2019_pos,
    num_wed_2019_pos,
    num_thu_2019_pos,
    num_fri_2019_pos,
]

res_2019["avg_pos"] = [
    avg_mon_2019_pos,
    avg_tue_2019_pos,
    avg_wed_2019_pos,
    avg_thu_2019_pos,
    avg_fri_2019_pos,
]

res_2019["stdev_pos"] = [
    stdev_mon_2019_pos,
    stdev_tue_2019_pos,
    stdev_wed_2019_pos,
    stdev_thu_2019_pos,
    stdev_fri_2019_pos,
]

In [65]:
res_2019.head()

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos
0,Mon,-0.000220,0.008255,22,-0.006271,0.007796,26,0.004900,0.004193
1,Tue,0.000753,0.007887,24,-0.005454,0.005199,28,0.006074,0.005556
2,Wed,0.000639,0.007329,19,-0.006000,0.007289,32,0.004581,0.003568
3,Thu,0.001727,0.007066,19,-0.004715,0.005971,31,0.005676,0.004215
4,Fri,0.002279,0.008930,18,-0.006195,0.007065,33,0.006901,0.005973

In [66]:
sum_tbls = [res_2016, res_2017, res_2018, res_2019]

In [67]:
res_2016["year"] = 2016
res_2017["year"] = 2017
res_2018["year"] = 2018
res_2019["year"] = 2019

spy_summary_df = pd.concat(sum_tbls, axis=0).reset_index(drop=True)

In [68]:
spy_summary_df.head(10)

,day,avg_return,stdev_return,num_neg,avg_neg,stdev_neg,num_pos,avg_pos,stdev_pos,year
0,Mon,0.000726,0.007204,20,-0.004873,0.005343,25,0.005233,0.005234,2016
1,Tue,0.000980,0.008423,20,-0.007061,0.005106,32,0.006005,0.005742,2016
2,Wed,0.000581,0.007656,24,-0.005499,0.005863,28,0.005792,0.004519,2016
3,Thu,0.000378,0.006878,23,-0.004820,0.005645,28,0.004648,0.004440,2016
4,Fri,-0.000291,0.010502,26,-0.006973,0.009026,24,0.006934,0.006802,2016
5,Mon,0.001321,0.003908,20,-0.001798,0.001596,26,0.003721,0.003432,2017
6,Tue,0.000397,0.004457,23,-0.003194,0.003072,27,0.003471,0.003000,2017
7,Wed,0.001061,0.004507,19,-0.002602,0.004096,33,0.003169,0.003223,2017
8,Thu,-0.000232,0.005003,25,-0.003806,0.004219,26,0.003203,0.002816,2017
9,Fri,0.001369,0.003009,20,-0.001569,0.000968,31,0.003264,0.002243,2017

In [69]:
# average returns by year and by day
spy_summary_df.groupby(["year", "day"])["avg_return"].mean()

year  day
2016  Fri   -0.000291
      Mon    0.000726
      Thu    0.000378
      Tue    0.000980
      Wed    0.000581
2017  Fri    0.001369
      Mon    0.001321
      Thu   -0.000232
      Tue    0.000397
      Wed    0.001061
2018  Fri   -0.001015
      Mon   -0.001001
      Thu   -0.000198
      Tue    0.000054
      Wed    0.000918
2019  Fri    0.002279
      Mon   -0.000220
      Thu    0.001727
      Tue    0.000753
      Wed    0.000639
Name: avg_return, dtype: float64

2016
- Best Day: Tuesday
- Worst Day: Friday

2017
- Best Day: Monday and Friday
- Worst Day: Thursday

2018
- Best Day: Wednesday
- Worst Day: Friday

2019
- Best Day: Thursday
- Worst Day: Monday

#### 3.2 are these days the same for your stock as they are for S&P-500?
- No, these results are not the same. No day stood at as the best year over year. However, the beginning and end of the week seem to be worst days for trading on the S&P 500 (Monday, Thursday, and Friday)

#### 4.1 You listen to the oracle and follow its advice. How much much money will you have on the last trading day of 2019?

In [70]:
dis_diff_l, dis_pct_diff_l = daily_ret_pct_diff(ac_l)
spy_diff_l, spy_pct_diff_l = daily_ret_pct_diff(spy_ac_l)

In [71]:
# if we listen to the advice, we only see positive increases and we avoid taking any losses

spy_cash = 100

for pct in spy_pct_diff_l:
    if pct >= 0:
        spy_cash = spy_cash * (1 + pct)
    else:
        spy_cash = spy_cash * (1)

print(
    "On the last day, with the Oracle's help, $100 investment in SPY yields, ${}".format(
        round(spy_cash), 2
    )
)

On the last day, with the Oracle's help, $100 investment in SPY yields, $11088

In [72]:
# if we listen to the advice, we only see positive increases and we avoid taking any losses

dis_cash = 100

for pct in dis_pct_diff_l:
    if pct >= 0:
        dis_cash = dis_cash * (1 + pct)
    else:
        dis_cash = dis_cash * (1)

print(
    "On the last day, with the Oracle's help, $100 investment in DIS yields, ${}".format(
        round(dis_cash), 2
    )
)

On the last day, with the Oracle's help, $100 investment in DIS yields, $92142

#### 5.1 Consider a "buy-and-hold" strategy. you buy on the first trading day and sell on the last day. So you do not listen to your oracle at all. As before, assume that you start with $100 for both your stock and "spy".

In [73]:
spy_cash = 100

for pct in spy_pct_diff_l:
    spy_cash = spy_cash * (1 + pct)

print(
    "On the last day, without the Oracle's help, $100 investment in SPY yields, ${}".format(
        round(spy_cash), 2
    )
)

On the last day, without the Oracle's help, $100 investment in SPY yields, $170

In [74]:
dis_cash = 100

for pct in dis_pct_diff_l:
    dis_cash = dis_cash * (1 + pct)

print(
    "On the last day, with the Oracle's help, $100 investment in DIS yields, ${}".format(
        round(dis_cash), 2
    )
)

On the last day, with the Oracle's help, $100 investment in DIS yields, $127

#### 5.2 How do these results compare with the results obtained in question 4?
- Orders of magnitude different. The buy-and-hold strategy yields minimal returns.

Question 6: Your oracle got very upset that you did not follow its advice. It decided to take revenge by giving you
wrong advice from time to time. Speci cally, let us consider the following three scenarios:
* (a) Oracle gave you wrong results for the best 10 trading days. In other words, you missed the best 10 days and your overall profit will be lower.

* (b) Oracle gave you wrong results for worst 10 trading days. In other words, you missed the worst 10 days and your overall profit will be higher.

* (c) Oracle gave you wrong results for best 5 days and for the worst 5 days.

In [75]:
# find the worst 10 trading  and remove them from the dataset then run cals

#### 6.1 For each of the scenarios above (a,b and c), compute the final amount that you will have for both your stock and "spy"

#### a. Find the best 10 trading days for SPY and DIS and remove them from the dataset then run calcs

In [76]:
# a. find the best 10 trading days for SPY and remove them from the dataset then run calcs
spy_pct_diff_idx = []
for i in range(len(spy_pct_diff_l)):
    spy_pct_diff_idx.append([spy_pct_diff_l[i], i])

spy_pct_diff_idx.sort()

sort_index = []
for x in spy_pct_diff_idx:
    sort_index.append(x[1])

# print(sort_index)

In [77]:
# remove the top ten from the list
excl_sort_index_a = sort_index[-10:]

In [78]:
sorted(excl_sort_index_a)

[750, 1046, 1048, 1052, 1055, 1057, 1062, 1064, 1071, 1073]

In [79]:
# find the daily returns without the top ten days
a_spy_pct_diff_l = []
for i in range(len(spy_pct_diff_l)):
    if i not in excl_sort_index_a:
        a_spy_pct_diff_l.append(spy_pct_diff_l[i])

In [80]:
# if we listen to the advice, we only see positive increases and we avoid taking any losses
# we will run this strategy on the new list

spy_cash = 100

for pct in a_spy_pct_diff_l:
    if pct >= 0:
        spy_cash = spy_cash * (1 + pct)
    else:
        spy_cash = spy_cash * (1)

print(
    "With scenario (a), $100 investment in SPY yields, ${}".format(round(spy_cash), 2)
)

With scenario (a), $100 investment in SPY yields, $6543

In [81]:
dis_pct_diff_idx = []
for i in range(len(dis_pct_diff_l)):
    dis_pct_diff_idx.append([dis_pct_diff_l[i], i])

dis_pct_diff_idx.sort()

sort_index = []
for x in dis_pct_diff_idx:
    sort_index.append(x[1])

# print(sort_index)

# remove the top ten from the list
excl_sort_index_a = sort_index[-10:]

# find the daily returns without the top ten days
a_dis_pct_diff_l = []
for i in range(len(dis_pct_diff_l)):
    if i not in excl_sort_index_a:
        a_dis_pct_diff_l.append(dis_pct_diff_l[i])

# if we listen to the advice, we only see positive increases and we avoid taking any losses
# we will run this strategy on the new list

dis_cash = 100

for pct in a_dis_pct_diff_l:
    if pct >= 0:
        dis_cash = dis_cash * (1 + pct)
    else:
        dis_cash = dis_cash * (1)

print(
    "With scenario (a), $100 investment in DIS yields, ${}".format(round(dis_cash), 2)
)

With scenario (a), $100 investment in DIS yields, $38868

#### b. Find the worst 10 trading days for SPY and DIS and include them in the dataset then run calcs

In [82]:
spy_pct_diff_idx = []
for i in range(len(spy_pct_diff_l)):
    spy_pct_diff_idx.append([spy_pct_diff_l[i], i])

spy_pct_diff_idx.sort()

sort_index = []
for x in spy_pct_diff_idx:
    sort_index.append(x[1])

# include the bottom ten from the list
incl_sort_index_b = sort_index[10:]

# find the change in $100 invested in SPY with the worst ten days included with the best days
spy_cash = 100

for i in range(len(spy_pct_diff_l)):
    pct = spy_pct_diff_l[i]
    if (pct > 0) | (i in incl_sort_index_b):
        spy_cash = spy_cash * (1 + pct)
    else:
        spy_cash = spy_cash * (1)

print(
    "With scenario (b), $100 investment in SPY yields, ${}".format(round(spy_cash), 2)
)

With scenario (b), $100 investment in SPY yields, $338

In [83]:
dis_pct_diff_idx = []
for i in range(len(dis_pct_diff_l)):
    dis_pct_diff_idx.append([spy_pct_diff_l[i], i])

dis_pct_diff_idx.sort()

sort_index = []
for x in dis_pct_diff_idx:
    sort_index.append(x[1])

# print(sort_index)

# include the bottom ten from the list
incl_sort_index_b = sort_index[10:]

# find the change in $100 invested in DIS with the worst ten days included with the best days
dis_cash = 100

for i in range(len(spy_pct_diff_l)):
    pct = spy_pct_diff_l[i]
    if (pct > 0) | (i in incl_sort_index_b):
        spy_cash = spy_cash * (1 + pct)
    else:
        spy_cash = spy_cash * (1)

print(
    "With scenario (b), $100 investment in DIS yields, ${}".format(round(dis_cash), 2)
)

With scenario (b), $100 investment in DIS yields, $100

#### c. Find the best 5 trading days for SPY and DIS and remove them from the dataset then run calcs. Find the worst 5 trading days for SPY and DIS and include them from the dataset.

In [84]:
# find the 5 best days for SPY and remove them from the dataset
spy_pct_diff_idx = []
for i in range(len(spy_pct_diff_l)):
    spy_pct_diff_idx.append([spy_pct_diff_l[i], i])

spy_pct_diff_idx.sort()

sort_index = []
for x in spy_pct_diff_idx:
    sort_index.append(x[1])

# print(sort_index)

# remove the top ten from the list
excl_sort_index_c = sort_index[-5:]

# include the bottom five from the list
incl_sort_index_c = sort_index[5:]

# find the change in $100 invested in SPY with the worst five days included with the five best days removed
spy_cash = 100

for i in range(len(spy_pct_diff_l)):
    if i not in excl_sort_index_c:
        pct = spy_pct_diff_l[i]
        if (pct > 0) | (i in incl_sort_index_c):
            spy_cash = spy_cash * (1 + pct)
        else:
            spy_cash = spy_cash * (1)

print(
    "With scenario (c), $100 investment in SPY yields, ${}".format(round(spy_cash), 2)
)

With scenario (c), $100 investment in SPY yields, $193

In [85]:
# find the 5 best days for DIS and remove them from the dataset
dis_pct_diff_idx = []
for i in range(len(dis_pct_diff_l)):
    dis_pct_diff_idx.append([dis_pct_diff_l[i], i])

dis_pct_diff_idx.sort()

sort_index = []
for x in dis_pct_diff_idx:
    sort_index.append(x[1])

# print(sort_index)

# remove the top ten from the list
excl_sort_index_c = sort_index[-5:]

# include the bottom five from the list
incl_sort_index_c = sort_index[5:]

# find the change in $100 invested in SPY with the worst five days included with the five best days removed
dis_cash = 100

for i in range(len(dis_pct_diff_l)):
    if i not in excl_sort_index_c:
        pct = dis_pct_diff_l[i]
        if (pct > 0) | (i in incl_sort_index_c):
            dis_cash = dis_cash * (1 + pct)
        else:
            dis_cash = dis_cash * (1)

print(
    "With scenario (c), $100 investment in DIS yields, ${}".format(round(dis_cash), 2)
)

With scenario (c), $100 investment in DIS yields, $132

#### 6.2 Do you gain more by missing the worst days? Or the best days?
- You gain more money by missing the 10 best days.

#### 6.3 are the results in part (c) different from results that you obtained in question 4?
- Yes, question 4 results are significantly higher; we did not miss any good days with question 4 scenario so the stock value continuously compounds by an average increase in return of almost .2 percentage points each year.